### ISSUE TITLE
Would you like to collaborate?

### ISSUE THREAD

**Issue by xlar54** [wiebow/d71-81writer.c128#1]
I have a library I wrote for the Ultimate: 

https://github.com/xlar54/ultimateii-dos-lib

Its in C, but your project would go great with it as a demo disk for the U64 and UII+ carts.  It would be great to have this as an addition.  Let me know, or let me know if I can include a C version of your work in my project.  Was also thinking a GEOS version of this would be quite useful to some.

**Comment by wiebow** [comment]
Sure, use what you want/need, that's why I put the source code online.
